{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
data:
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ .Values.global.zipkinTracingURL }}
  SPRING_ZIPKIN_BASEURL: {{ .Values.global.zipkinBaseURL }}
  SPRING_CONFIG_IMPORT: {{ .Values.global.configServerURL }}
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .Values.global.eurekaServerURL }}
{{- end -}}