# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gateway-server-deployment
deploymentLabel: gateway-server
appName: gateway-server

replicaCount: 1

image:
  repository: docker.io/avalc/gateway-server
  tag: latest
  imagePullPolicy: IfNotPresent

containerPort: 8765

service:
  type: LoadBalancer
  port: 8765
  targetPort: 8765

config_enabled: true
zipkin_enabled: true
eureka_enabled: true
appname_enabled: true
keycloak_enabled: true