version: '3.8'

services:
  accounts-service:
    image: avalc/accounts-service
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-app-network
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
        SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka

  loans-service:
    image: avalc/loans-service
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bank-app-network
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka

  cards-service:
    image: avalc/cards-service
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bank-app-network
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
        SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka

  config-server:
    image: avalc/config-server
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - bank-app-network

  eureka-server:
    image: avalc/eureka-server
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - bank-app-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888

  gateway-server:
    image: avalc/gateway-server
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - bank-app-network
    depends_on:
      - config-server
      - eureka-server
      - accounts-service
      - loans-service
      - cards-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka

networks:
  bank-app-network: