version: '3.8'

services:

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - bank-app-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bank-app-network

  accounts-service:
    image: avalc/accounts-service
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-app-network
    depends_on:
      - rabbitmq
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
        SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
        SPRING_PROFILES_ACTIVE: h2,zipkin,rabbitmq
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:8411/
        RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWKSETURI: http://keycloak:8080/realms/master/protocol/openid-connect/certs
        SPRING.SECURITY.OAUTH2.CLIENT.PROVIDER.KEYCLOAK.TOKENURI: http://keycloak:8080/realms/master/protocol/openid-connect/token

  loans-service:
    image: avalc/loans-service
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bank-app-network
    depends_on:
      - rabbitmq
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_PROFILES_ACTIVE: h2,zipkin,rabbitmq
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:8411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWKSETURI: http://keycloak:8080/realms/master/protocol/openid-connect/certs
      SPRING.SECURITY.OAUTH2.CLIENT.PROVIDER.KEYCLOAK.TOKENURI: http://keycloak:8080/realms/master/protocol/openid-connect/token

  cards-service:
    image: avalc/cards-service
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bank-app-network
    depends_on:
      - rabbitmq
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
        SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
        SPRING_PROFILES_ACTIVE: h2,zipkin,rabbitmq
        SPRING.ZIPKIN.BASEURL: http://zipkin-server:8411/
        RABBIT_URI: amqp://guest:guest@rabbitmq:5672
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWKSETURI: http://keycloak:8080/realms/master/protocol/openid-connect/certs
        SPRING.SECURITY.OAUTH2.CLIENT.PROVIDER.KEYCLOAK.TOKENURI: http://keycloak:8080/realms/master/protocol/openid-connect/token

  config-server:
    image: avalc/config-server
    mem_limit: 700m
    depends_on:
      - rabbitmq
    ports:
      - "8888:8888"
    networks:
      - bank-app-network

  eureka-server:
    image: avalc/eureka-server
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - bank-app-network
    depends_on:
      - rabbitmq
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888

  gateway-server:
    image: avalc/gateway-server
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - bank-app-network
    depends_on:
      - rabbitmq
      - config-server
      - eureka-server
      - accounts-service
      - loans-service
      - cards-service
      - keycloak
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_PROFILES_ACTIVE: zipkin,rabbitmq
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:8411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.JWKSETURI: http://keycloak:8080/realms/master/protocol/openid-connect/certs

  zipkin-server:
    image: openzipkin/zipkin:2.24
    mem_limit: 300m
    ports:
      - "8411:9411"
    networks:
      - bank-app-network
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3.9.29-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bank-app-network

  keycloak:
      image: quay.io/keycloak/keycloak:22.0.1
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      restart: unless-stopped
      volumes:
        - keycloak:/opt/keycloak/data/
      ports:
        - "7080:8080"
      networks:
        - bank-app-network
      command:
        - start-dev

volumes:
  keycloak:

networks:
  bank-app-network: