# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards-service
appName: cards-service

replicaCount: 1

image:
  repository: docker.io/avalc/cards-service
  tag: latest
  imagePullPolicy: IfNotPresent

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

config_enabled: true
zipkin_enabled: true
eureka_enabled: true
appname_enabled: true
keycloak_enabled: false