apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-configmap
data:
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-service:8411/api/v2/spans
  SPRING_CONFIG_IMPORT: configserver:http://config-server-service:8888/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-service:8761/eureka/