apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          imagePullPolicy: IfNotPresent
          image: docker.io/avalc/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: bankapp-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888