apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  labels:
    app: cards-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-service
  template:
    metadata:
      labels:
        app: cards-service
    spec:
      containers:
        - name: cards-service
          imagePullPolicy: IfNotPresent
          image: docker.io/avalc/cards-service:latest
          ports:
            - containerPort: 9000
          env:
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: bankapp-configmap
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: bankapp-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: bankapp-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: cards-k8s-service
spec:
  selector:
    app: cards-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000