# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: zipkin-deployment
deploymentLabel: zipkin
appName: zipkin

replicaCount: 1

image:
  repository: openzipkin/zipkin
  tag: 2.24
  imagePullPolicy: IfNotPresent

containerPort: 9411

service:
  type: LoadBalancer
  port: 9411
  targetPort: 9411

config_enabled: false
zipkin_enabled: false
eureka_enabled: false
appname_enabled: false
keycloak_enabled: false