# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eureka-server-deployment
deploymentLabel: eureka-server
appName: eureka-server

replicaCount: 1

image:
  repository: docker.io/avalc/eureka-server
  tag: latest
  imagePullPolicy: IfNotPresent

containerPort: 8761

service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

config_enabled: true
zipkin_enabled: false
eureka_enabled: false
appname_enabled: true
keycloak_enabled: false